name: Gulp build and commit updated stylesheets

on: [push]

jobs:
  gulp-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Compile with gulp
        uses: elstudio/actions-js-build/build@v4

      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: Regenerate assets for views